version: '3.9'

services:
  ubuntu:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
      no_cache: false
    container_name: ubuntu
    restart: unless-stopped
    tty: true
    environment:
      DOMAINS: ""
    ports:
      - "443:443"
    volumes:
      - ./.vscode:/workspace/.vscode
      - ./app:/workspace/app
